#!/bin/bash
#
# Ülesanne 2: arvutab kasutaja sisestatud täisarvu numbrite summa (while-tsükliga)
#
read -p "Sisesta suvaline täisarv: " sisend

if ! [[ $sisend =~ ^-?[0-9]+$ ]]; then
    echo "Viga: $sisend ei ole täisarv"
    exit 1
fi

arv=$sisend
summa=0
while [ $arv -ne 0 ]; do
    number=$(( arv % 10 ))
    summa=$(( summa + number ))
    arv=$(( arv / 10 ))
done
echo "Arvu $sisend numbrite summa on $summa"
# skripti lõpp
