#!/bin/bash
#
# Ülesanne 4: kontrollib while-tsükliga, kas sisestatud arv on algarv
#
read -p "Sisesta suvaline arv: " arv

if ! [[ $arv =~ ^[0-9]+$ ]]; then
    echo "Viga: $arv ei ole positiivne täisarv"
    exit 1
fi

if [ $arv -lt 2 ]; then
    echo "$arv - ei ole algarv"
    exit 0
fi

jagaja=2
while [ $(( arv % jagaja )) -ne 0 ]; do
    jagaja=$(( jagaja + 1 ))
done

if [ $jagaja -eq $arv ]; then
    echo "$arv - on algarv"
else
    echo "$arv - ei ole algarv"
fi
# skripti lõpp
